### PR TITLE
Hotfix: Period Start/end Refactor

### PR DESCRIPTION
**Pull request by SiravitPhokeed**
This basically changed all period times from an object with just hours, minutes, and seconds determining the start time into an actual `Date`. This was done to prepare for Attachments.

### CODE REVIEW

**Comment by SiravitPhokeed** [comment]
Wait a sec, forgot to push

**Review by smartwhatt — APPROVED** [review]
LGTM
man

**Comment by SiravitPhokeed** [comment]
Can I have @IHasDiabetes review this?

**Comment by smartwhatt** [comment]
Yea

**Review by ImSadudee — APPROVED** [review]
LGTM!

**Pull request merged**
